#!/usr/bin/env bash
# bootstrap-signing.sh — create Config/Signing.xcconfig if missing.
#
# project.yml references `Config/Signing.xcconfig` as the base xcconfig for both
# Debug and Release. The Config/ directory is gitignored (generated by xcodegen
# for plists/entitlements). This script makes sure the xcconfig file exists so
# `xcodegen generate` doesn't warn and Xcode picks up your team automatically.
#
# Usage:
#   ./scripts/bootstrap-signing.sh                 # creates Config/Signing.xcconfig with empty DEVELOPMENT_TEAM
#   APPLE_TEAM_ID=ABCD1234EF ./scripts/bootstrap-signing.sh   # writes the supplied team ID
#
# After the file exists, you can edit it by hand to add your DEVELOPMENT_TEAM
# (a 10-char alphanumeric value from developer.apple.com/account).
# CI overwrites this file from the APPLE_TEAM_ID secret on every run — see
# .github/workflows/release-testflight.yml.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$REPO_ROOT/Config"
XCCONFIG="$CONFIG_DIR/Signing.xcconfig"
TEAM_ID="${APPLE_TEAM_ID:-}"

mkdir -p "$CONFIG_DIR"

if [[ -f "$XCCONFIG" && -z "$TEAM_ID" ]]; then
  echo "bootstrap-signing: $XCCONFIG already exists (leaving as-is)."
  exit 0
fi

cat > "$XCCONFIG" <<EOF
// Signing.xcconfig — generated by scripts/bootstrap-signing.sh
// This file is gitignored (Config/ is in .gitignore). Edit it locally to set
// your Apple Developer Team ID; CI overwrites it from the APPLE_TEAM_ID secret.
//
// Find your team ID at https://developer.apple.com/account (top right) or in
// Xcode → Settings → Accounts → your team → Team ID.

DEVELOPMENT_TEAM = ${TEAM_ID}
CODE_SIGN_STYLE = Automatic
EOF

if [[ -n "$TEAM_ID" ]]; then
  echo "bootstrap-signing: wrote $XCCONFIG with DEVELOPMENT_TEAM=$TEAM_ID"
else
  echo "bootstrap-signing: wrote $XCCONFIG with empty DEVELOPMENT_TEAM."
  echo "  → Edit it to add your team ID, e.g. DEVELOPMENT_TEAM = ABCD1234EF"
fi
